// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace StudentsClubsWeb.Data.Compiled
{
    public partial class AppDbContextModel
    {
        partial void Initialize()
        {
            var appUserClub = AppUserClubEntityType.Create(this);
            var identityRole = IdentityRoleEntityType.Create(this);
            var identityRoleClaimstring = IdentityRoleClaimstringEntityType.Create(this);
            var identityUser = IdentityUserEntityType.Create(this);
            var identityUserClaimstring = IdentityUserClaimstringEntityType.Create(this);
            var identityUserLoginstring = IdentityUserLoginstringEntityType.Create(this);
            var identityUserRolestring = IdentityUserRolestringEntityType.Create(this);
            var identityUserTokenstring = IdentityUserTokenstringEntityType.Create(this);
            var club = ClubEntityType.Create(this);
            var clubAdmin = ClubAdminEntityType.Create(this);
            var joinClubRequest = JoinClubRequestEntityType.Create(this);
            var post = PostEntityType.Create(this);
            var tag = TagEntityType.Create(this);
            var appUser = AppUserEntityType.Create(this, identityUser);

            AppUserClubEntityType.CreateForeignKey1(appUserClub, club);
            AppUserClubEntityType.CreateForeignKey2(appUserClub, appUser);
            IdentityRoleClaimstringEntityType.CreateForeignKey1(identityRoleClaimstring, identityRole);
            IdentityUserClaimstringEntityType.CreateForeignKey1(identityUserClaimstring, identityUser);
            IdentityUserLoginstringEntityType.CreateForeignKey1(identityUserLoginstring, identityUser);
            IdentityUserRolestringEntityType.CreateForeignKey1(identityUserRolestring, identityRole);
            IdentityUserRolestringEntityType.CreateForeignKey2(identityUserRolestring, identityUser);
            IdentityUserTokenstringEntityType.CreateForeignKey1(identityUserTokenstring, identityUser);
            ClubAdminEntityType.CreateForeignKey1(clubAdmin, appUser);
            ClubAdminEntityType.CreateForeignKey2(clubAdmin, club);
            JoinClubRequestEntityType.CreateForeignKey1(joinClubRequest, club);
            JoinClubRequestEntityType.CreateForeignKey2(joinClubRequest, appUser);
            PostEntityType.CreateForeignKey1(post, appUser);
            PostEntityType.CreateForeignKey2(post, club);
            TagEntityType.CreateForeignKey1(tag, appUser);
            TagEntityType.CreateForeignKey2(tag, club);
            TagEntityType.CreateForeignKey3(tag, post);

            ClubEntityType.CreateSkipNavigation1(club, appUser, appUserClub);
            AppUserEntityType.CreateSkipNavigation1(appUser, club, appUserClub);

            AppUserClubEntityType.CreateAnnotations(appUserClub);
            IdentityRoleEntityType.CreateAnnotations(identityRole);
            IdentityRoleClaimstringEntityType.CreateAnnotations(identityRoleClaimstring);
            IdentityUserEntityType.CreateAnnotations(identityUser);
            IdentityUserClaimstringEntityType.CreateAnnotations(identityUserClaimstring);
            IdentityUserLoginstringEntityType.CreateAnnotations(identityUserLoginstring);
            IdentityUserRolestringEntityType.CreateAnnotations(identityUserRolestring);
            IdentityUserTokenstringEntityType.CreateAnnotations(identityUserTokenstring);
            ClubEntityType.CreateAnnotations(club);
            ClubAdminEntityType.CreateAnnotations(clubAdmin);
            JoinClubRequestEntityType.CreateAnnotations(joinClubRequest);
            PostEntityType.CreateAnnotations(post);
            TagEntityType.CreateAnnotations(tag);
            AppUserEntityType.CreateAnnotations(appUser);

            AddAnnotation("ProductVersion", "6.0.15");
        }
    }
}
